name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine regex
    - name: Patch version number
      run: |
        import regex as re
        # settings
        tag = '${{ github.ref }}'[10:]
        path = './nfem/__init__.py'
        # get version string from tag
        pattern = 'v(\d+)(?:\.(\d+)(?:\.(\d+)(?:\.(\d+))?)?)?$'
        match = re.match(pattern, tag)
        if match is None:
            raise RuntimeError('Invalid version tag')
        version = '.'.join(filter(lambda x: x is not None, match.groups()))
        # patch
        with open(path, 'r') as file:
            data = file.read()
        data = data.replace("__version__ = 'dev'", f"__version__ = '{version}'")
        with open(path, 'w') as file:
            file.write(data)
      shell: python
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
